language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
  licenses:
  - android-sdk-license-.+
before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
script:
  - ./gradlew clean assembleDevRelease